CLASS z2ui6_cl_http_handler DEFINITION PUBLIC INHERITING FROM z2ui6_cl_ui5_http_handler.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS z2ui6_cl_http_handler IMPLEMENTATION.

ENDCLASS.
